### ISSUE TITLE
Empty link text

### ISSUE THREAD

**Issue by tricinel** [jackdomleo7/Checka11y.css#60] opened 2020-10-06 13:01 UTC
### Describe the new a11y feature or project enhancement

Anchor tags that are missing link text should probably be highlighted. I think the same could apply for buttons. It's not common, but it happened to me with frameworks where the property being accessed to display the link text was missing or came in as an empty string from the db. The linter won't catch this since `<a href="">{{ title }}</a>` is valid, but the output `<a href=""></a>` is not :)

### Describe the solution you'd like

A quick code pen: https://codepen.io/tricinel/pen/gOMYBWx

**Comment by alvaromontoro** [comment] 2020-10-06 13:12
This looks like #34 (I should have made it clearer and separate button/a requests.)

There is one case in which `<a>` can be empty and still be valid: when used as an anchor instead of a link:

```html
<a name="deep-link"></a>
```

The selector from the demo would need to be adjusted slightly to only select the anchors that have an `href` attribute.

**Comment by tricinel** [comment] 2020-10-06 13:14
Ah great, sorry, I missed that one :) That looks like it gathered more attention too, so I'd be more than happy to close this. Would be happy to do it by the way.

**Comment by jackdomleo7** [comment] 2020-10-07 08:01
No worries, but good to see we're all thinking alike 😊

**Comment by jackdomleo7** [comment] 2020-10-07 08:02
No worries, but good to see we're all thinking alike 😊

Closing since this is a duplicate of #34.

**Closed by jackdomleo7** 2020-10-07 08:02 UTC
Labels: duplicate

**Comment by tricinel** [comment] 2020-10-07 09:20
@jackdomleo7 yep, sounds good. Is #34 up for grabs?

**Comment by jackdomleo7** [comment] 2020-10-07 09:26
@tricinel Sure, comment on #34 so I can assign you.
